# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='baseline_cross',
            field=models.BooleanField(default=False),
        ),
    ]
