# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0003_teamdata_gears_placed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(default=0)),
                ('team_number', models.PositiveIntegerField(default=0)),
                ('baseline_crossed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeleopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(default=0)),
                ('team_number', models.PositiveIntegerField(default=0)),
                ('gears_placed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='baseline_cross',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='gears_placed',
        ),
    ]
