# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0004_auto_20170226_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodata',
            name='auto_fuel_accuracy',
            field=models.IntegerField(choices=[(0, b'did not attempt'), (1, b'poor accuracy'), (2, b'A few went in'), (3, b'Half went in'), (4, b'over half went in'), (5, b'100% accuracy')], default=0),
        ),
        migrations.AddField(
            model_name='autodata',
            name='auto_fuel_speed',
            field=models.IntegerField(choices=[(0, b'did not attempt'), (1, b'<1 ball/sec'), (2, b'1 ball/sec'), (3, b'3 balls/sec'), (4, b'5+ balls/sec'), (5, b'faster than the speed of light')], default=0),
        ),
        migrations.AddField(
            model_name='autodata',
            name='auto_gears_placed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autodata',
            name='hopper_efficiency',
            field=models.IntegerField(choices=[(0, b'did not attempt'), (1, b'less than 5 balls caught'), (2, b'Almost ten balls caught'), (3, b'over ten balls caught'), (4, b'only dropped a few'), (5, b'collected every single ball')], default=0),
        ),
        migrations.AddField(
            model_name='teleopdata',
            name='fuel_floor_intake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teleopdata',
            name='teleop_fuel_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teleopdata',
            name='teleop_fuel_speed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
