# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0005_auto_20170228_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teleopdata',
            name='fuel_floor_intake',
        ),
        migrations.AddField(
            model_name='teleopdata',
            name='robot_speed',
            field=models.IntegerField(choices=[(0, b'did not move'), (1, b'real slow'), (2, b'slower than average'), (3, b'average speed'), (4, b'faster than average'), (5, b'B00Lin')], default=0),
        ),
        migrations.AlterField(
            model_name='autodata',
            name='auto_gears_placed',
            field=models.IntegerField(choices=[(0, b'none placed'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7')], default=0),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='gears_placed',
            field=models.IntegerField(choices=[(0, b'none placed'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7')], default=0),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='teleop_fuel_accuracy',
            field=models.IntegerField(choices=[(0, b'did not attempt'), (1, b'poor accuracy'), (2, b'A few went in'), (3, b'Half went in'), (4, b'over half went in'), (5, b'100% accuracy')], default=0),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='teleop_fuel_speed',
            field=models.PositiveIntegerField(choices=[(0, b'did not attempt'), (1, b'<1 ball/sec'), (2, b'1 ball/sec'), (3, b'3 balls/sec'), (4, b'5+ balls/sec'), (5, b'faster than the speed of light')], default=0),
        ),
    ]
