# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0006_auto_20170228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleopdata',
            name='pilot_rating',
            field=models.CharField(choices=[('not present', 'not present'), ('dropped every gear', 'dropped every gear'), ('dropped 1-2 gears', 'dropped 1-2 gears'), ('no gears dropped', 'no gears dropped')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='robot_speed',
            field=models.CharField(choices=[('meh real slow', 'meh real slow'), ('about average', 'about average'), ('BOOLIN', 'BOOLIN')], default=0, max_length=100),
        ),
    ]
