# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0007_auto_20170228_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleopdata',
            name='climber_success',
            field=models.CharField(choices=[('did not attempt', 'did not attempt'), ('did not press button', 'did not press button'), ('fell off rope', 'fell off rope'), ('rope snapped', 'rope snapped'), ('climbed successfully', 'climbed successfully')], default=0, max_length=100),
        ),
    ]
