# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0008_teleopdata_climber_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='alliance_color',
            field=models.CharField(choices=[('Blue Alliance', 'Blue Alliance'), ('Red Alliance', 'Red Alliance')], default=0, max_length=100),
        ),
    ]
