# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0009_teamdata_alliance_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_alliance', models.CharField(choices=[('Blue Alliance', 'Blue Alliance'), ('Red Alliance', 'Red Alliance')], default=0, max_length=100)),
                ('alliance_money', models.IntegerField(default=0)),
                ('match_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(default='noob', max_length=100)),
                ('scout_password', models.CharField(default='password', max_length=100)),
                ('scout_sheckles', models.IntegerField(default=0)),
            ],
        ),
    ]
