# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0010_bethandler_scout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scout',
            name='scout_name',
        ),
        migrations.RemoveField(
            model_name='scout',
            name='scout_password',
        ),
        migrations.RemoveField(
            model_name='scout',
            name='scout_sheckles',
        ),
        migrations.AddField(
            model_name='scout',
            name='scout_scheckles',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scout',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='teleopdata',
            name='winning_alliance',
            field=models.CharField(choices=[('Blue Alliance', 'Blue Alliance'), ('Red Alliance', 'Red Alliance')], default=0, max_length=100),
        ),
    ]
