# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0011_auto_20170301_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scout',
            old_name='scout_scheckles',
            new_name='scout_sheckles',
        ),
    ]
