# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-04 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0012_auto_20170301_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=0, max_length=100)),
                ('match_number', models.IntegerField(default=0)),
                ('alliance_bet_on', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
