# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0013_bet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bethandler',
            old_name='alliance_money',
            new_name='money_in_pot',
        ),
        migrations.RemoveField(
            model_name='bethandler',
            name='bet_alliance',
        ),
        migrations.AddField(
            model_name='bet',
            name='money_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bethandler',
            name='winning_alliance',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
