# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0017_remove_teleopdata_pilot_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='matches_scouted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='winning_alliance',
            field=models.CharField(choices=[('PLEASE SELECT THE WINNER', 'PLEASE SELECT THE WINNER'), ('Blue Alliance', 'Blue Alliance'), ('Red Alliance', 'Red Alliance')], default=0, max_length=100),
        ),
    ]
