# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0018_auto_20170311_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodata',
            name='auto_gears_placed',
            field=models.IntegerField(choices=[(0, b'none placed'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11')], default=0),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='gears_placed',
            field=models.IntegerField(choices=[(0, b'none placed'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11')], default=0),
        ),
    ]
