# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0021_auto_20170316_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gear_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
