# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0023_otherdata_team_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodata',
            name='hopper_efficiency',
            field=models.CharField(choices=[('did not attempt', 'did not attempt'), ('less than 5 balls caught', 'less than 5 balls caught'), ('almost ten balls caught', 'Almost ten balls caught'), ('over ten balls caught', 'over ten balls caught'), ('only dropped a few', 'only dropped a few'), ('collected every ball', 'collected every single ball')], default=0, max_length=100),
        ),
    ]
