# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0029_auto_20170326_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleopdata',
            name='robot_strat',
            field=models.CharField(choices=[('Defense', 'Defense'), ('Gear Cycling', 'Gear Cycling'), ('Fuel Shooting', 'Fuel Shooting'), ('Other (comment)', 'Other (see comments)')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='autodata',
            name='gear_attempted',
            field=models.CharField(choices=[(' ', ' '), ('did not attempt', 'did not attempt'), ('pilot error', 'pilot error'), ('gear in bot', 'gear in bot'), ('missed the peg', 'missed the peg'), ('successfully placed', 'successfully placed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='autodata',
            name='peg_placed_on',
            field=models.CharField(choices=[(' ', ' '), ('did not attempt', 'did not attempt'), ('left peg', 'left peg'), ('center peg', 'center peg'), ('right peg', 'right peg')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='climber_success',
            field=models.CharField(choices=[(' ', ' '), ('did not attempt', 'did not attempt'), ('did not press button', 'did not press button'), ('fell off rope', 'fell off rope'), ('rope snapped', 'rope snapped'), ('climbed successfully', 'climbed successfully')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='teleopdata',
            name='winning_alliance',
            field=models.CharField(choices=[(' ', ' '), ('Blue Alliance', 'Blue Alliance'), ('Red Alliance', 'Red Alliance')], default=0, max_length=100),
        ),
    ]
